name: Build Sound Bank

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Run Build Script
        run: ./gen.cs

      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: sound-bank-artifact
          path: WilhelmSFX.sf3

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: "Latest Build"
          body: "Automated build from master branch."
          prerelease: true
          files: |
            WilhelmSFX.sf3
